Add Berlin2
indieweb/2019.indieweb.org pull request #91
Opened 2019-10-13 05:42 UTC by RosemaryOrchard

Added Berlin2 (copied from Berlin, dates and links changed)

2019-10-13 05:56 UTC, tantek commented on templates/berlin2/schedule.php
> +  <i class="calendar icon"></i> <time class="dt-start" datetime="2019-05-04">May 4</time>-<time class="dt-end" datetime="2019-05-05">5</time>, 2019<br>
```suggestion
  <i class="calendar icon"></i> <time class="dt-start" datetime="2019-11-23">November 23</time>-<time class="dt-end" datetime="2019-11-24">24</time>, 2019<br>
```

2019-10-13 05:57 UTC, tantek commented on templates/berlin2/schedule.php
> +       <li><span class="time">10:30</span> Introduction</li>
```suggestion
       <li><span class="time">10:00</span> Introduction</li>
```

2019-10-13 05:57 UTC, tantek commented on templates/berlin2/schedule.php
> +       <li><span class="time">10:45</span> Keynote</li>
```suggestion
       <li><span class="time">10:15</span> Keynote</li>
```

2019-10-13 05:58 UTC, tantek commented on templates/berlin2/schedule.php
> +       <li><span class="time">10:00</span> Day 2 kick-off</li>
```suggestion
       <li><span class="time">9:30</span> Doors Open</li>
       <li><span class="time">10:00</span> Day 2 kick-off</li>
```

2019-10-13 05:58 UTC, tantek commented on templates/berlin2/schedule.php
> +<p>Schedule is subject to change. View the <a href="https://indieweb.org/2019/Berlin/Schedule">full schedule grid</a> on the IndieWeb wiki for the latest updates.</p>
```suggestion
<p>Schedule is subject to change. View the <a href="https://indieweb.org/2019/Berlin2/Schedule">full schedule grid</a> on the IndieWeb wiki for the latest updates.</p>
```

2019-10-13 06:00 UTC, tantek requested changes
Suggested a bunch of fixes. Take a look.

2019-10-13 07:01 UTC, RosemaryOrchard reviewed
Commit all changes I hope?

2019-10-14 18:47 UTC, tantek approved these changes
Looks good!

2019-10-14 18:47 UTC, RosemaryOrchard reviewed
Fix duplicate doors opening

2019-10-17 15:18 UTC, merged